import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Container, TextField } from "@mui/material";
import { Box } from "@mui/system";
import Typography from "@mui/material/Typography";
import { useState } from "react";
import dynamic from "next/dynamic";
import { WheelData } from "react-custom-roulette/dist/components/Wheel/types";
const Wheel = dynamic(
  () => import("react-custom-roulette").then((mod) => mod.Wheel),
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [listOfFilms, setListOfFilms] = useState<string[]>([]);
  const [currentFilm, setCurrentFilm] = useState("");
  const [mustSpin, setMustSpin] = useState(false);
  const [prizeNumber, setPrizeNumber] = useState(0);

  const renderFilmAddSection = () => {
    return (
      <Box display="flex" marginBottom={3}>
        <TextField
          label="Film to watch"
          variant="outlined"
          sx={{ marginRight: "2rem" }}
          value={currentFilm}
          onChange={(e) => setCurrentFilm(e.target.value)}
        />
        <Button
          variant="contained"
          onClick={() => {
            if (currentFilm) {
              setListOfFilms((prevState) => [...prevState, currentFilm]);
            }
            setCurrentFilm("");
          }}
        >
          Add to list
        </Button>
      </Box>
    );
  };

  const renderWheelSpinnerSection = () => {
    if (!listOfFilms.length) {
      return (
        <Typography textAlign="center">
          The magic wheel will appear when a film is added to the list
        </Typography>
      );
    }

    const handleSpinClick = () => {
      const newPrizeNumber = Math.floor(Math.random() * listOfFilms.length);
      setPrizeNumber(newPrizeNumber);
      setMustSpin(true);
    };

    const filmData: WheelData[] = listOfFilms.map((film, index) => ({
      option: film,
      style: { backgroundColor: index % 2 === 0 ? "green" : "yellow" },
    }));

    return (
      <Box display="flex" flexDirection="column" alignItems="center">
        <Wheel
          mustStartSpinning={mustSpin}
          prizeNumber={prizeNumber}
          data={filmData}
          onStopSpinning={() => {
            setMustSpin(false);
          }}
        />
        <Button onClick={handleSpinClick} variant="contained">
          SPIN
        </Button>
      </Box>
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          padding: "2rem",
          minHeight: "100vh",
        }}
      >
        <Box display="flex">
          <Typography
            variant="h1"
            marginBottom={4}
            textAlign="center"
            sx={{
              fontSize: {
                xs: "1.5rem",
                md: "1.75rem",
                lg: "2rem",
              },
              lineHeight: { xs: "0.75rem", md: "1rem" },
            }}
          >
            Seb & Almu's Fabulous&nbsp;
            <Box
              sx={{
                display: {
                  md: "none",
                },
              }}
            >
              <br />
            </Box>
            Movie Picking Wheel!
          </Typography>
        </Box>
        {renderFilmAddSection()}
        {renderWheelSpinnerSection()}
      </Container>
    </>
  );
}
